# Generated by Django 5.0.6 on 2024-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dingtion', '0002_relay_relay_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Cihaz', 'verbose_name_plural': 'Cihazlar'},
        ),
        migrations.AlterModelOptions(
            name='relay',
            options={'verbose_name': 'Röle', 'verbose_name_plural': 'Röleler'},
        ),
        migrations.AlterModelOptions(
            name='userdevice',
            options={'verbose_name': 'Kullanıcı Cihazı', 'verbose_name_plural': 'Kullanıcı Cihazları'},
        ),
        migrations.AlterModelOptions(
            name='userrelaypermission',
            options={'verbose_name': 'Kullanıcı Cihaz İzini', 'verbose_name_plural': 'Kullanıcı Cihaz İzinleri'},
        ),
        migrations.AddField(
            model_name='relay',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='relay_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
